language: r
latex: false

install:
- R -q -e 'install.packages(c("curl", "remotes")); remotes::install_github("ropenscilabs/tic")'

script:
- R -q -e 'setwd("/usr/local/lib/R"); name <- paste0("ticpkg-", gsub("^([^.]*)[.]([^.]*)[.].*$", "\\1-\\2", getRversion()), ".tar.xz"); print(name); exit <- system(paste0("tar caf ", name, " site-library")); stopifnot(exit == 0)'
- R -q -e 'installed.packages()[, "Version", drop = FALSE]'
- ls -hl

#env
env:
  global:
  - MAKEFLAGS="-j 2"

r:
- 3.1
- 3.2
- oldrel
- release
- devel
