language: r
cache: packages
latex: false

install:
- R -q -e 'install.packages("remotes"); update.packages(ask = FALSE); remotes::install_github("ropenscilabs/tic")'

script:
- tar cvf ticpkg.tar.gz `R -q -e '.libPaths()[[1]]'`
- ls -hl

#env
env:
  global:
  - MAKEFLAGS="-j 2"
