language: r
cache: packages
script:
- R -q -e 'install.packages("remotes"); update.packages(ask = FALSE); remotes::install_packages("tic")'
- tar cvf ticpkg.tar.gz $(R -q -e '.libPaths()[[1]]')

#env
env:
  global:
  - MAKEFLAGS="-j 2"
