language: r
cache: packages
latex: false

install:
- R -q -e 'install.packages("remotes"); update.packages(ask = FALSE); remotes::install_github("ropenscilabs/tic")'

script:
- tar caf ticpkg.tar.xz /home/travis/R/Library
- R -q -e 'sessionInfo()'
- ls -hl

#env
env:
  global:
  - MAKEFLAGS="-j 2"
